services:
  nexus:
    platform: "linux/amd64"
    image: sonatype/nexus3
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ${NEXUS_REPOSITORY_PATH}:/nexus-data
    ports:
      - "8443:8443"
      - "8082:8082"
      - "8083:8083"

# On linux: sudo chown -R 200:200 ./nexus_data