FROM debian:12-slim AS fmd-emulator_arm64

# add arm64 architecture as workaround for apt-get update on linux amd64
#RUN dpkg --add-architecture arm64
#RUN sed -i "s/deb h/deb [arch=amd64] h/g" /etc/apt/sources.list
#RUN apt update

RUN apt update && apt install -y --no-install-recommends \
    libc6 libdbus-1-3 libfontconfig1 libgcc1 nano \
    libpulse0 libtinfo5 libx11-6 libxcb1 libxdamage1 \
    libnss3 libxcomposite1 libxcursor1 libxi6 \
    libxext6 libxfixes3 zlib1g libgl1 pulseaudio pulseaudio-utils socat \
    iputils-ping curl ca-certificates wget unzip procps rsync net-tools \
    xz-utils python3 bison make gawk gcc dbus f2fs-tools libpcre2-16-0

################################
# Install Java
################################
RUN mkdir -p /usr/local/jdk-21
WORKDIR /usr/local/jdk-21
RUN wget https://download.oracle.com/java/21/latest/jdk-21_linux-aarch64_bin.tar.gz
RUN tar --strip-components=1 -xf jdk-21_linux-aarch64_bin.tar.gz
ENV JAVA_HOME=/usr/local/jdk-21
ENV PATH=$JAVA_HOME/bin:$PATH

################################
# Install pulse audio default config
################################
COPY ./emulator/default.pa /etc/pulse/default.pa

################################
# Install Android SDK and tools
################################
RUN mkdir -p /android/sdk/cmdline-tools/latest && mkdir -p /android/sdk/avd && mkdir -p /android/sdk/platforms  \
    && mkdir -p /android/sdk/platform-tools && mkdir -p /android/sdk/system-images  \
    && mkdir /android/tmp && mkdir -p /android/user_home/ && mkdir -p /android/sdk/system-images/android/arm64-v8a/
WORKDIR /android
RUN wget https://dl.google.com/android/repository/commandlinetools-mac-11076708_latest.zip
RUN unzip commandlinetools-mac-11076708_latest.zip  -d /android/tmp
RUN mv /android/tmp/cmdline-tools/* /android/sdk/cmdline-tools/latest/
RUN apt install -y android-sdk-platform-tools
RUN cp /usr/lib/android-sdk/platform-tools/* /android/sdk/platform-tools/

ENV ANDROID_HOME=/android/sdk
ENV ANDROID_SDK_ROOT=/android/sdk
ENV ANDROID_AVD_HOME=/android/sdk/avd
ENV ANDROID_EMULATOR_HOME=/android/sdk/emulator
ENV ANDROID_USER_HOME=/android/user_home/
ENV PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
ENV PATH=$ANDROID_HOME/platform-tools:$PATH
ENV PATH=$ANDROID_HOME/emulator/:$PATH
ENV REPO_OS_OVERRIDE=macosx

################################
# Copy adbkey and adbkey.pub
################################
COPY ./emulator/prebuilts/adb/adbkey /android/sdk/emulator/adbkey
COPY ./emulator/prebuilts/adb/adbkey.pub /android/sdk/emulator/adbkey.pub

################################
# Prepare Android emulator using prebuilt ARM64 binary
################################
COPY ./emulator/prebuilts/arm64/sdk-repo-linux_aarch64-emulator-11774154.zip /android/
RUN unzip /android/sdk-repo-linux_aarch64-emulator-11774154.zip -d /android/sdk/
COPY ./emulator/avd/ /android/sdk/avd/

################################
# Install and start SSH        #
################################
RUN apt-get update && apt-get install -y --no-install-recommends openssh-server fail2ban
RUN mkdir /var/run/sshd
RUN mkdir -p /root/.ssh
COPY ./emulator/prebuilts/ssh/id_rsa.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys
RUN chown root:root /root/.ssh/authorized_keys
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin without-password/' /etc/ssh/sshd_config

COPY ./emulator/prebuilts/fail2ban/jail.local /etc/fail2ban/jail.local
RUN service ssh start
RUN service fail2ban start

################################
# Set environment variables in .bashrc
################################
RUN echo 'export JAVA_HOME=/usr/local/jdk-21' >> /root/.bashrc
RUN echo 'export ANDROID_HOME=/android/sdk' >> /root/.bashrc
RUN echo 'export ANDROID_SDK_ROOT=/android/sdk' >> /root/.bashrc
RUN echo 'export ANDROID_AVD_HOME=/android/sdk/avd' >> /root/.bashrc
RUN echo 'export ANDROID_EMULATOR_HOME=/android/sdk/emulator' >> /root/.bashrc
RUN echo 'export ANDROID_USER_HOME=/android/user_home/' >> /root/.bashrc
RUN echo 'export PATH=$JAVA_HOME/bin:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH' >> /root/.bashrc
RUN echo 'export REPO_OS_OVERRIDE=macosx' >> /root/.bashrc

