version: '3.7'
services:
  android_emulator_development_amd64:
    platform: "linux/amd64"
    container_name: android_emulator_development_adm64
    build:
      context: ..
      dockerfile: emulator/Dockerfile
    devices: [/dev/kvm]
    env_file:
      - .env
    ports:
      - "8554:8554"
      - "5555:5555"

  android_emulator_development_arm64:
    platform: "linux/arm64"
    container_name: android_emulator_development_arm64
    build:
      context: ..
      dockerfile: emulator/Dockerfile_arm64
    command: sleep infinity
    env_file:
      - .env
    ports:
      - "8554:8554"
      - "5555:5555"
