FROM fmd-emulator_arm64

################################
# Copy system image
################################
COPY ./image_artefacts/ /android/sdk/system-images/android/

###################################
# Create start script
###################################
RUN service ssh start

# Start SSH
CMD ["rm -f /tmp/restart"]
