FROM fmd-emulator_x86_64

################################
# Copy system image
################################
COPY ./image_artefacts/x86_64/ /android/sdk/system-images/android/x86_64/

###################################
# Create start script
###################################
COPY ./emulator/emulator_start.sh /android/
RUN chmod +x /android/emulator_start.sh

CMD ["bash", "-c", "/android/emulator_start.sh"]
