services:
  envoy:
    platform: {{ platform }}
    image: envoyproxy/envoy:v1.27-latest
    restart: unless-stopped
    command: /docker-entrypoint-initdb.d/init_envoy.sh
    volumes:
      - ./env/envoy/init_envoy.sh:/docker-entrypoint-initdb.d/init_envoy.sh
      - ./env/envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./env/envoy/fmd-aosp.init-lab.ch/:/etc/envoy/certs/
      - ./public/.well-known/:/var/www/certbot/.well-known/
    ports:{% for line in envoy_port_mapping %}
      {{ line }}{% endfor %}
    networks:
      - frontend

  mitmproxy:
    image: mitmproxy/mitmproxy
    ports:
      - "8081:8081"
      - "8080:8080"
    command: "mitmweb --web-host 0.0.0.0"
    networks:
      - android

  coturn:
    platform: {{ platform }}
    image: coturn/coturn
    restart: unless-stopped
    volumes:
      - ./env/coturn/turnserver.conf:/etc/coturn/turnserver.conf
    network_mode: "host"
{% for line in emulator_content_list %}
  {{ line }}
{% endfor %}


networks:
  frontend:
    driver: bridge
  android:
