services:
#  nginx:
#    image: nginx:latest
#    restart: unless-stopped
#    volumes:
#      - ./env/nginx/public:/usr/share/nginx/html
#      - ./env/nginx/nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "80:80"
#    networks:
#      - frontend

  envoy:
    platform: {{ platform }}
    image: envoyproxy/envoy:v1.27-latest
    restart: unless-stopped
    command: /docker-entrypoint-initdb.d/init_envoy.sh
    volumes:
      - ./env/envoy/init_envoy.sh:/docker-entrypoint-initdb.d/init_envoy.sh
      - ./env/envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./env/envoy/amy.cloudlab.zhaw.ch/:/etc/envoy/certs/
      - ./public/.well-known/:/var/www/certbot/.well-known/
    ports:{% for line in envoy_port_mapping %}
      {{ line }}{% endfor %}
    networks:
      - frontend

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    env_file:
      - ./env/pihole/.env
    ports:
      - "8082:80"
    networks:
      android:
        ipv4_address: 172.28.0.2
    restart: unless-stopped

  mitmproxy:
    image: mitmproxy/mitmproxy
    ports:
      - "8081:8081"
      - "8080:8080"
    command: "mitmweb --web-host 0.0.0.0"
    networks:
      - android

  adb_streamer:
    container_name: adb_streamer
    hostname: adb_streamer
    build:
      context: ./adb_streaming_service
      dockerfile: 'Dockerfile'
    ports:
      - '9001:9001'
    restart: always
    env_file:
      - ./env/adb_streamer/.env
    networks:
      - android
    volumes:
      - './adb_streaming_service/source/apps:/app/source/apps'
      - ./env/adb_streamer/fmd.cert:/app/source/env/certs/fmd.crt
      - ./env/adb_streamer/fmd.key:/app/source/env/certs/fmd.key

  coturn:
    platform: {{ platform }}
    image: coturn/coturn
    restart: unless-stopped
    volumes:
      - ./env/coturn/turnserver.conf:/etc/coturn/turnserver.conf
    network_mode: "host"
{% for line in emulator_content_list %}
  {{ line }}
{% endfor %}


networks:
  frontend:
    driver: bridge
  android:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          aux_addresses:
            pihole: 172.28.0.2

